---
kind: pipeline
type: docker
name: default-build

steps:
  - name: check
    image: publicawesome/networks-check
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
  - name: collect
    image: publicawesome/stargaze:develop
    commands:
      - sh ./check.sh
  - name: collect
    image: publicawesome/stargaze:develop
    commands:
      - sh ./run.sh
trigger:
  event:
    - pull_request

---
kind: signature
hmac: 6163436b23843d78fb74ba8697b4f11efb463b96be65c1cce235c245a1181510

...
