---
kind: pipeline
type: docker
name: default-build

steps:
  - name: check
    image: publicawesome/networks-check
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
  - name: collect
    image: publicawesome/stargaze:develop
    commands:
      - sh ./check.sh
  - name: collect
    image: publicawesome/stargaze:develop
    commands:
      - sh ./check.sh
trigger:
  event:
    - pull_request

---
kind: signature
hmac: b93e41fbb68268a7e333fdab874d2ee9fe4052c96809d0daa3dd28407c5eb8d1

...
